### ISSUE TITLE
module 'tensorflow' has no attribute 'ConfigProto'

### ISSUE THREAD

**Issue by amitkml** [pythonlessons/Reinforcement_Learning#1]
I have done the TF backport changes by adding %tensorflow_version 1.x

but still getting the error...
TensorFlow is already loaded. Please restart the runtime to change versions. So is this tested in tensorflow 1.x or TF 2?

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-3-d4b99b39e7d5> in <module>()
     21 
     22 # configure Keras and TensorFlow sessions and graph
---> 23 config = tf.ConfigProto()
     24 config.gpu_options.allow_growth = True
     25 sess = tf.Session(config=config)

AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

**Comment by pythonlessons** [comment]
Made it with tf 1.15
